### ISSUE TITLE
Make match samples valid against SportsML XML Schema

### ISSUE THREAD

**Issue by pauljkelly** [iptc/sport-schema#113]
soccer match samples 2-5 still have xml validation errors. Get rid of them

**Comment by bquinn** [comment]
Here's a summary of the errors:

1. Many instances of "sequence-number" that are date-time instances instead of integers, eg:

```
    <action class="spactionclass:play" id="a.2290448091"
              sequence-number="2021-04-24T12:30:55.897" minutes-elapsed="0" time-elapsed="00:06"
              last-modified="2021-04-24T19:28:50" period-value="1" team-idref="TFBB4"
              start-location="22.5,33.9" end-location="30.0,25.8"
              angle="5.7" length="9.6"
              pass-method="socpass:head"
              type="socact:pass-complete">
              <participant idref="p.57145" role="socpartrole:passer"/>
            </action>
```
which gives the error `samples/xml/sportsml/soccer-match-05.xml:747: element action: Schemas validity error : Element '{http://iptc.org/std/nar/2006-10-01/}action', attribute 'sequence-number': '2021-04-24T12:30:55.897' is not a valid value of the atomic type 'xs:integer'.`

2. Attribute which shouldn't be there: "length", "opposite-play", "infraction-level" (ironically given that we're adding it to sport schema but it's not in SportsML), "related-action", "score-attempt-description", 'stage-name' (on tournament-part-metadata), 

e.g.:
```
          <action class="spactionclass:play" id="a.2290448157"
              sequence-number="2021-04-24T12:30:59.006" minutes-elapsed="0" time-elapsed="00:09"
              last-modified="2021-04-24T19:29:24" period-value="1" team-idref="TFBB14"
              start-location="60.7,67.2" end-location="54.2,51.8"
               length="12.5"
              angle="4.1" type="socact:pass-complete">
              <participant idref="p.41733" role="socpartrole:passer"/>
            </action>
```

which gives the error `samples/xml/sportsml/soccer-match-05.xml:783: element action: Schemas validity error : Element '{http://iptc.org/std/nar/2006-10-01/}action', attribute 'length': The attribute 'length' is not allowed.`

3. Some badly formed patterns

eg

`samples/xml/sportsml/soccer-match-05.xml:13175: element action: Schemas validity error : Element '{http://iptc.org/std/nar/2006-10-01/}action', attribute 'result': [facet 'pattern'] The value 'socplayresult:' is not accepted by the pattern '[^\s:]+:[^\s]+'.`

**Comment by pauljkelly** [comment]
Done!
